### ISSUE TITLE
Unable to set the Path for Primitier.exe.

### ISSUE THREAD

**Issue by abonChannel** [TotalJTM/PrimitierCreativeMode#1]
I cannot set the Path for Primitire.exe.
When I drag the exe file, nothing responds and I cannot proceed.

Environment used
OS: Windows 11 Pro build 22000.556
CPU:Ryzen 5 3600 4420MHz (virtualization enabled)
RAM:DDR4 32GB 3400MHz

**Comment by abon-san** [comment]
I opened too many tabs in my browser and sent the wrong one...
